version: "2"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: shrink_link
      POSTGRES_PASSWORD: 7777
      PGDATA: /tmp
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432" # container:host
  web:
    build: . 
    command: npm run dev
    image: node
    links:
      - db
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: shrink_link
      PGPASSWORD: 7777
      PGPORT: 5432
      JWTSECRET: 123456 
    depends_on: 
      - db
    volumes:
      - .:/app/
      - /app/node_modules
    ports: 
      - "5000:5000"
  