version: "2"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pass
      PGDATA: /tmp
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432" # container:host
  web:
    build: . 
    command: npm run dev
    image: node
    links:
      - db
    environment:
      PGHOST: db
      PGUSER: user
      PGDATABASE: db
      PGPASSWORD: pass
      PGPORT: 5432
      JWTSECRET: secret 
      STRIPESECRET: secret
      NODEMAILER_EMAIL: email,
      NODEMAILER_PASSWORD: emailPassword
    depends_on: 
      - db
    volumes:
      - .:/app/
      - /app/node_modules
    ports: 
      - "5000:5000"
  